-- The database under ./db is autogenerated. Changing the entries there
-- will result in a data loss whenever a new database gets extracted.
-- To be able to customize and/or fix entries that aren't yet detected
-- by the extractor logic, this file here can be used to save overwrites.

do -- area trigger
end

do -- items
end

do -- units/npcs
  pfDB["units"]["data-vanillaplus"][2299] = { }   -- Borgus Stoutarm (Alliance - Burning Steppes)
  pfDB["units"]["data-vanillaplus"][2941] = { }   -- Lanie Reed (Alliance - Searing Gorge)
  pfDB["units"]["data-vanillaplus"][3305] = { }   -- Grisha (Horde - Searing Gorge)
  pfDB["units"]["data-vanillaplus"][10583] = { }  -- Gryfe (Neutral - Un'Goro)
  pfDB["units"]["data-vanillaplus"][10897] = { }  -- Sindrayl (Alliance - Moonglade)
  pfDB["units"]["data-vanillaplus"][12596] = { }  -- Bibilfaz Featherwhistle (Alliance - Western Plaguelands)
  pfDB["units"]["data-vanillaplus"][12740] = { }  -- Faustron (Horde - Moonglade)
  pfDB["units"]["data-vanillaplus"][13177] = { }  -- Vahgruk (Horde - Burning Steppes)
  pfDB["units"]["data-vanillaplus"][14242] = { }  -- Sulhasa (Horde - Silithus)
end

do -- quests
  -- Add "Dark Iron Gunpowder Keg" to objectives of "Vile Dwarven Pigs"
  -- The extractor scripts did not catch those, as the objetive is filled via a Gossip on use.
  -- pfDB["quests"]["data-vanillaplus"][41682]["obj"]["O"] = { 2020173 }

  -- Add "Head of Geshgan" to the loot table of "Geshgan"
  -- This can be removed by the next database export
  -- pfDB["items"]["data-vanillaplus"][41783]["U"] = { [62217] = 1.0 }
end
